# Generated by Django 3.1 on 2023-01-16 14:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldborderjson',
            name='area',
        ),
        migrations.RemoveField(
            model_name='worldborderjson',
            name='fips',
        ),
        migrations.RemoveField(
            model_name='worldborderjson',
            name='iso2',
        ),
        migrations.RemoveField(
            model_name='worldborderjson',
            name='iso3',
        ),
        migrations.RemoveField(
            model_name='worldborderjson',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='worldborderjson',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='worldborderjson',
            name='name',
        ),
        migrations.RemoveField(
            model_name='worldborderjson',
            name='pop2005',
        ),
        migrations.RemoveField(
            model_name='worldborderjson',
            name='region',
        ),
        migrations.RemoveField(
            model_name='worldborderjson',
            name='subregion',
        ),
        migrations.RemoveField(
            model_name='worldborderjson',
            name='un',
        ),
        migrations.AddField(
            model_name='worldborderjson',
            name='diameter',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='worldborderjson',
            name='l_scaled',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='worldborderjson',
            name='label',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='worldborderjson',
            name='objectid',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='worldborderjson',
            name='shape_leng',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='worldborderjson',
            name='v',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='worldborderjson',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
        ),
    ]
