# Generated by Django 3.1 on 2023-01-16 18:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20230116_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakHotspot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevation', models.FloatField(default=0.5)),
                ('emitter_k', models.FloatField(default=0.5)),
                ('label', models.CharField(default='', max_length=80)),
                ('p', models.FloatField(default=0.5)),
                ('runid', models.CharField(default='', max_length=80)),
                ('leak', models.FloatField(default=0.5)),
                ('color', models.CharField(default='', max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
