# Generated by Django 3.1 on 2023-01-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_leakhotspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldborder',
            name='nname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
