# Generated by Django 3.1 on 2023-01-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_worldborder_nname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevation', models.FloatField(default=0.5)),
                ('emitter_k', models.FloatField(default=0.5)),
            ],
        ),
    ]
